# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np
list = [1,2,3,4,5]
array_list = np.array([1,2,3,4,5])

In [5]:
print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [16]:
list = [1,2,3,4,5]
array_list = np.array([1,2,3,4,5])
for i in list:
    print("list type",type(i))
    
for i in array_list :
    print("array_list type",type(i))


list type <class 'int'>
list type <class 'int'>
list type <class 'int'>
list type <class 'int'>
list type <class 'int'>
array_list type <class 'numpy.int64'>
array_list type <class 'numpy.int64'>
array_list type <class 'numpy.int64'>
array_list type <class 'numpy.int64'>
array_list type <class 'numpy.int64'>


# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.


In [25]:
list = [1,2,3,4,5]
array_list = np.array(object = list_, dtype = int)

In [26]:
for i in list:
    print(type(i))

for i in array_list:
    print(type(i))


<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)

In [27]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [29]:
shape = num_array.shape
size = num_array.size

print("shape of num_array",shape)
print("size of num_array",size)

shape of num_array (2, 3)
size of num_array 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [40]:
zero_matrix = np.zeros([3,3])

In [41]:
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [ ]:
matrix = np.